/*
Every Go program consists of packages.
The program starts at the "main" package.
Packages can be imported to use their functions and types, and the name of the package is typically the last part of its import path.

*/

package main // package declaration

import (
	"fmt" // import statement
	"math/rand"
)

func main() {
	fmt.Println("My favorite number is", rand.Intn(10))
}

/* output ;
$ go run packages.go
My favorite number is 4

Note everytime you run the program, the output will be different because of the random number generated by the rand package.
*/
